export const GET_ALL_ARTIFACTS_REQUESTS = 'GET_ALL_ARTIFACTS_REQUESTS'
export const GET_ALL_ARTIFACTS_SUCCESS = 'GET_ALL_ARTIFACTS_SUCCESS'
export const GET_ALL_ARTIFACTS_FAIL = 'GET_ALL_ARTIFACTS_FAIL'

export const GET_ARTIFACT_BY_FEED_ENTRY_REQUEST = 'GET_ARTIFACT_BY_FEED_ENTRY_REQUEST'
export const GET_ARTIFACT_BY_FEED_ENTRY_SUCCESS = 'GET_ARTIFACT_BY_FEED_ENTRY_SUCCESS'
export const GET_ARTIFACT_BY_FEED_ENTRY_FAIL = 'GET_ARTIFACT_BY_FEED_ENTRY_FAIL'

export const ARTIFACT_CREATE_REQUEST = 'ARTIFACT_CREATE_REQUEST'
export const ARTIFACT_CREATE_SUCCESS = 'ARTIFACT_CREATE_SUCCESS'
export const ARTIFACT_CREATE_FAIL = 'ARTIFACT_CREATE_FAIL'

export const GET_ARTIFACT_REQUEST = 'GET_ARTIFACT_REQUEST'
export const GET_ARTIFACT_SUCCESS = 'GET_ARTIFACT_SUCCESS'
export const GET_ARTIFACT_FAIL = 'GET_ARTIFACT_FAIL'

export const UPDATE_ARTIFACT_REQUEST = 'UPDATE_ARTIFACT_REQUEST'
export const UPDATE_ARTIFACT_SUCCESS = 'UPDATE_ARTIFACT_SUCCESS'
export const UPDATE_ARTIFACT_FAIL = 'UPDATE_ARTIFACT_FAIL'

export const FILTER_ARTIFACT_REQUEST = 'FILTER_ARTIFACT_REQUEST'
export const FILTER_ARTIFACT_SUCCESS = 'FILTER_ARTIFACT_SUCCESS'
export const FILTER_ARTIFACT_FAIL = 'FILTER_ARTIFACT_FAIL'

export const SEARCH_ARTIFACT_REQUEST = 'SEARCH_ARTIFACT_REQUEST'
export const SEARCH_ARTIFACT_SUCCESS = 'SEARCH_ARTIFACT_SUCCESS'
export const SEARCH_ARTIFACT_FAIL = 'SEARCH_ARTIFACT_FAIL'

export const TEST_ARTIFACTS_REQUEST = 'TEST_ARTIFACTS_REQUEST'
export const TEST_ARTIFACTS_SUCCESS = 'TEST_ARTIFACTS_SUCCESS'
export const TEST_ARTIFACTS_FAIL = 'TEST_ARTIFACTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
