export const AWS_CUSTOMER_CREATE_REQUEST = 'AWS_CUSTOMER_CREATE_REQUEST'
export const AWS_CUSTOMER_CREATE_SUCCESS = 'AWS_CUSTOMER_CREATE_SUCCESS'
export const AWS_CUSTOMER_CREATE_FAIL = 'AWS_CUSTOMER_CREATE_FAIL'

export const GET_ALL_AWS_CUSTOMERS_REQUEST = 'GET_ALL_AWS_CUSTOMERS_REQUEST'
export const GET_ALL_AWS_CUSTOMERS_SUCCESS = 'GET_ALL_AWS_CUSTOMERS_SUCCESS'
export const GET_ALL_AWS_CUSTOMERS_FAIL = 'GET_ALL_AWS_CUSTOMERS_FAIL'

export const GET_AWS_CUSTOMER_REQUEST = 'GET_AWS_CUSTOMER_REQUEST'
export const GET_AWS_CUSTOMER_SUCCESS = 'GET_AWS_CUSTOMER_SUCCESS'
export const GET_AWS_CUSTOMER_FAIL = 'GET_AWS_CUSTOMER_FAIL'

export const UPDATE_AWS_CUSTOMER_REQUEST = 'UPDATE_AWS_CUSTOMER_REQUEST'
export const UPDATE_AWS_CUSTOMER_SUCCESS = 'UPDATE_AWS_CUSTOMER_SUCCESS'
export const UPDATE_AWS_CUSTOMER_FAIL = 'UPDATE_AWS_CUSTOMER_FAIL'

export const FILTER_AWS_CUSTOMER_REQUEST = 'FILTER_AWS_CUSTOMER_REQUEST'
export const FILTER_AWS_CUSTOMER_SUCCESS = 'FILTER_AWS_CUSTOMER_SUCCESS'
export const FILTER_AWS_CUSTOMER_FAIL = 'FILTER_AWS_CUSTOMER_FAIL'

export const SEARCH_AWS_CUSTOMER_REQUEST = 'SEARCH_AWS_CUSTOMER_REQUEST'
export const SEARCH_AWS_CUSTOMER_SUCCESS = 'SEARCH_AWS_CUSTOMER_SUCCESS'
export const SEARCH_AWS_CUSTOMER_FAIL = 'SEARCH_AWS_CUSTOMER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
