export const GET_ALL_CUSTOMERS_REQUESTS = 'GET_ALL_CUSTOMERS_REQUESTS'
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS'
export const GET_ALL_CUSTOMERS_FAIL = 'GET_ALL_CUSTOMERS_FAIL'

export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL'

export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST'
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'
export const GET_CUSTOMER_FAIL = 'GET_CUSTOMER_FAIL'

export const UPDATE_CUSTOMER_REQUEST = 'UPDATE_CUSTOMER_REQUEST'
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS'
export const UPDATE_CUSTOMER_FAIL = 'UPDATE_CUSTOMER_FAIL'

export const FILTER_CUSTOMER_REQUEST = 'FILTER_CUSTOMER_REQUEST'
export const FILTER_CUSTOMER_SUCCESS = 'FILTER_CUSTOMER_SUCCESS'
export const FILTER_CUSTOMER_FAIL = 'FILTER_CUSTOMER_FAIL'

export const GET_L0_CUSTOMER_REQUEST = 'GET_L0_CUSTOMER_REQUEST'
export const GET_L0_CUSTOMER_SUCCESS = 'GET_L0_CUSTOMER_SUCCESS'
export const GET_L0_CUSTOMER_FAIL = 'GET_L0_CUSTOMER_FAIL'

export const GET_L1_CUSTOMER_REQUEST = 'GET_L1_CUSTOMER_REQUEST'
export const GET_L1_CUSTOMER_SUCCESS = 'GET_L1_CUSTOMER_SUCCESS'
export const GET_L1_CUSTOMER_FAIL = 'GET_L1_CUSTOMER_FAIL'

export const GET_L2_CUSTOMER_REQUEST = 'GET_L2_CUSTOMER_REQUEST'
export const GET_L2_CUSTOMER_SUCCESS = 'GET_L2_CUSTOMER_SUCCESS'
export const GET_L2_CUSTOMER_FAIL = 'GET_L2_CUSTOMER_FAIL'

export const GET_L3_CUSTOMER_REQUEST = 'GET_L3_CUSTOMER_REQUEST'
export const GET_L3_CUSTOMER_SUCCESS = 'GET_L3_CUSTOMER_SUCCESS'
export const GET_L3_CUSTOMER_FAIL = 'GET_L3_CUSTOMER_FAIL'

export const SEARCH_CUSTOMER_REQUEST = 'SEARCH_CUSTOMER_REQUEST'
export const SEARCH_CUSTOMER_SUCCESS = 'SEARCH_CUSTOMER_SUCCESS'
export const SEARCH_CUSTOMER_FAIL = 'SEARCH_CUSTOMER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
