export const GET_ALL_DATA_CENTERS_REQUEST = 'GET_ALL_DATA_CENTERS_REQUEST'
export const GET_ALL_DATA_CENTERS_SUCCESS = 'GET_ALL_DATA_CENTERS_SUCCESS'
export const GET_ALL_DATA_CENTERS_FAIL = 'GET_ALL_DATA_CENTERS_FAIL'

export const DATA_CENTER_CREATE_REQUEST = 'DATA_CENTER_CREATE_REQUEST'
export const DATA_CENTER_CREATE_SUCCESS = 'DATA_CENTER_CREATE_SUCCESS'
export const DATA_CENTER_CREATE_FAIL = 'DATA_CENTER_CREATE_FAIL'

export const GET_DATA_CENTER_REQUEST = 'GET_DATA_CENTER_REQUEST'
export const GET_DATA_CENTER_SUCCESS = 'GET_DATA_CENTER_SUCCESS'
export const GET_DATA_CENTER_FAIL = 'GET_DATA_CENTER_FAIL'

export const UPDATE_DATA_CENTER_REQUEST = 'UPDATE_DATA_CENTER_REQUEST'
export const UPDATE_DATA_CENTER_SUCCESS = 'UPDATE_DATA_CENTER_SUCCESS'
export const UPDATE_DATA_CENTER_FAIL = 'UPDATE_DATA_CENTER_FAIL'

export const FILTER_DATA_CENTER_REQUEST = 'FILTER_DATA_CENTER_REQUEST'
export const FILTER_DATA_CENTER_SUCCESS = 'FILTER_DATA_CENTER_SUCCESS'
export const FILTER_DATA_CENTER_FAIL = 'FILTER_DATA_CENTER_FAIL'

export const SEARCH_DATA_CENTER_REQUEST = 'SEARCH_DATA_CENTER_REQUEST'
export const SEARCH_DATA_CENTER_SUCCESS = 'SEARCH_DATA_CENTER_SUCCESS'
export const SEARCH_DATA_CENTER_FAIL = 'SEARCH_DATA_CENTER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
