export const GET_ALL_FEED_ENTRIES_REQUESTS = 'GET_ALL_FEED_ENTRIES_REQUESTS'
export const GET_ALL_FEED_ENTRIES_SUCCESS = 'GET_ALL_FEED_ENTRIES_SUCCESS'
export const GET_ALL_FEED_ENTRIES_FAIL = 'GET_ALL_FEED_ENTRIES_FAIL'

export const GET_APPROVED_FEED_ENTRIES_REQUESTS = 'GET_APPROVED_FEED_ENTRIES_REQUESTS'
export const GET_APPROVED_FEED_ENTRIES_SUCCESS = 'GET_APPROVED_FEED_ENTRIES_SUCCESS'
export const GET_APPROVED_FEED_ENTRIES_FAIL = 'GET_APPROVED_FEED_ENTRIES_FAIL'

export const GET_COMPLETED_FEED_ENTRIES_REQUESTS = 'GET_COMPLETED_FEED_ENTRIES_REQUESTS'
export const GET_COMPLETED_FEED_ENTRIES_SUCCESS = 'GET_COMPLETED_FEED_ENTRIES_SUCCESS'
export const GET_COMPLETED_FEED_ENTRIES_FAIL = 'GET_COMPLETED_FEED_ENTRIES_FAIL'

export const FEED_ENTRY_CREATE_REQUEST = 'FEED_ENTRY_CREATE_REQUEST'
export const FEED_ENTRY_CREATE_SUCCESS = 'FEED_ENTRY_CREATE_SUCCESS'
export const FEED_ENTRY_CREATE_FAIL = 'FEED_ENTRY_CREATE_FAIL'

export const GET_FEED_ENTRY_REQUEST = 'GET_FEED_ENTRY_REQUEST'
export const GET_FEED_ENTRY_SUCCESS = 'GET_FEED_ENTRY_SUCCESS'
export const GET_FEED_ENTRY_FAIL = 'GET_FEED_ENTRY_FAIL'

export const UPDATE_FEED_ENTRY_REQUEST = 'UPDATE_FEED_ENTRY_REQUEST'
export const UPDATE_FEED_ENTRY_SUCCESS = 'UPDATE_FEED_ENTRY_SUCCESS'
export const UPDATE_FEED_ENTRY_FAIL = 'UPDATE_FEED_ENTRY_FAIL'

export const UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_REQUEST =
  'UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_REQUEST'
export const UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_SUCCESS =
  'UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_SUCCESS'
export const UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_FAIL = 'UPDATE_BY_CURRENT_VALUE_FEED_ENTRY_FAIL'

export const FILTER_FEED_ENTRY_REQUEST = 'FILTER_FEED_ENTRY_REQUEST'
export const FILTER_FEED_ENTRY_SUCCESS = 'FILTER_FEED_ENTRY_SUCCESS'
export const FILTER_FEED_ENTRY_FAIL = 'FILTER_FEED_ENTRY_FAIL'

export const SEARCH_FEED_ENTRY_REQUEST = 'SEARCH_FEED_ENTRY_REQUEST'
export const SEARCH_FEED_ENTRY_SUCCESS = 'SEARCH_FEED_ENTRY_SUCCESS'
export const SEARCH_FEED_ENTRY_FAIL = 'SEARCH_FEED_ENTRY_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
