export const GET_ALL_LOGGER_CUSTOMERS_REQUEST = 'GET_ALL_LOGGER_CUSTOMERS_REQUEST'
export const GET_ALL_LOGGER_CUSTOMERS_SUCCESS = 'GET_ALL_LOGGER_CUSTOMERS_SUCCESS'
export const GET_ALL_LOGGER_CUSTOMERS_FAIL = 'GET_ALL_LOGGER_CUSTOMERS_FAIL'

export const LOGGER_CUSTOMER_CREATE_REQUEST = 'LOGGER_CUSTOMER_CREATE_REQUEST'
export const LOGGER_CUSTOMER_CREATE_SUCCESS = 'LOGGER_CUSTOMER_CREATE_SUCCESS'
export const LOGGER_CUSTOMER_CREATE_FAIL = 'LOGGER_CUSTOMER_CREATE_FAIL'

export const GET_LOGGER_CUSTOMER_REQUEST = 'GET_LOGGER_CUSTOMER_REQUEST'
export const GET_LOGGER_CUSTOMER_SUCCESS = 'GET_LOGGER_CUSTOMER_SUCCESS'
export const GET_LOGGER_CUSTOMER_FAIL = 'GET_LOGGER_CUSTOMER_FAIL'

export const UPDATE_LOGGER_CUSTOMER_REQUEST = 'UPDATE_LOGGER_CUSTOMER_REQUEST'
export const UPDATE_LOGGER_CUSTOMER_SUCCESS = 'UPDATE_LOGGER_CUSTOMER_SUCCESS'
export const UPDATE_LOGGER_CUSTOMER_FAIL = 'UPDATE_LOGGER_CUSTOMER_FAIL'

export const FILTER_LOGGER_CUSTOMER_REQUEST = 'FILTER_LOGGER_CUSTOMER_REQUEST'
export const FILTER_LOGGER_CUSTOMER_SUCCESS = 'FILTER_LOGGER_CUSTOMER_SUCCESS'
export const FILTER_LOGGER_CUSTOMER_FAIL = 'FILTER_LOGGER_CUSTOMER_FAIL'

export const SEARCH_LOGGER_CUSTOMER_REQUEST = 'SEARCH_LOGGER_CUSTOMER_REQUEST'
export const SEARCH_LOGGER_CUSTOMER_SUCCESS = 'SEARCH_LOGGER_CUSTOMER_SUCCESS'
export const SEARCH_LOGGER_CUSTOMER_FAIL = 'SEARCH_LOGGER_CUSTOMER_FAIL'

export const GET_ALL_LOGGER_PRODUCTS_REQUEST = 'GET_ALL_LOGGER_PRODUCTS_REQUEST'
export const GET_ALL_LOGGER_PRODUCTS_SUCCESS = 'GET_ALL_LOGGER_PRODUCTS_SUCCESS'
export const GET_ALL_LOGGER_PRODUCTS_FAIL = 'GET_ALL_LOGGER_PRODUCTS_FAIL'

export const LOGGER_PRODUCT_CREATE_REQUEST = 'LOGGER_PRODUCT_CREATE_REQUEST'
export const LOGGER_PRODUCT_CREATE_SUCCESS = 'LOGGER_PRODUCT_CREATE_SUCCESS'
export const LOGGER_PRODUCT_CREATE_FAIL = 'LOGGER_PRODUCT_CREATE_FAIL'

export const GET_LOGGER_PRODUCT_REQUEST = 'GET_LOGGER_PRODUCT_REQUEST'
export const GET_LOGGER_PRODUCT_SUCCESS = 'GET_LOGGER_PRODUCT_SUCCESS'
export const GET_LOGGER_PRODUCT_FAIL = 'GET_LOGGER_PRODUCT_FAIL'

export const UPDATE_LOGGER_PRODUCT_REQUEST = 'UPDATE_LOGGER_PRODUCT_REQUEST'
export const UPDATE_LOGGER_PRODUCT_SUCCESS = 'UPDATE_LOGGER_PRODUCT_SUCCESS'
export const UPDATE_LOGGER_PRODUCT_FAIL = 'UPDATE_LOGGER_PRODUCT_FAIL'

export const FILTER_LOGGER_PRODUCT_REQUEST = 'FILTER_LOGGER_PRODUCT_REQUEST'
export const FILTER_LOGGER_PRODUCT_SUCCESS = 'FILTER_LOGGER_PRODUCT_SUCCESS'
export const FILTER_LOGGER_PRODUCT_FAIL = 'FILTER_LOGGER_PRODUCT_FAIL'

export const SEARCH_LOGGER_PRODUCT_REQUEST = 'SEARCH_LOGGER_PRODUCT_REQUEST'
export const SEARCH_LOGGER_PRODUCT_SUCCESS = 'SEARCH_LOGGER_PRODUCT_SUCCESS'
export const SEARCH_LOGGER_PRODUCT_FAIL = 'SEARCH_LOGGER_PRODUCT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
