export const GET_ALL_MITRE_REQUESTS = 'GET_ALL_MITRE_REQUESTS'
export const GET_ALL_MITRE_SUCCESS = 'GET_ALL_MITRE_SUCCESS'
export const GET_ALL_MITRE_FAIL = 'GET_ALL_MITRE_FAIL'

export const UPDATE_MITRE_REQUEST = 'UPDATE_MITRE_REQUEST'
export const UPDATE_MITRE_SUCCESS = 'UPDATE_MITRE_SUCCESS'
export const UPDATE_MITRE_FAIL = 'UPDATE_MITRE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
