export const GET_ML_MODEL_REQUEST = 'GET_ML_MODEL_REQUEST'
export const GET_ML_MODEL_SUCCESS = 'GET_ML_MODEL_SUCCESS'
export const GET_ML_MODEL_FAIL = 'GET_ML_MODEL_FAIL'

export const UPDATE_ML_MODEL_REQUEST = 'UPDATE_ML_MODEL_REQUEST'
export const UPDATE_ML_MODEL_SUCCESS = 'UPDATE_ML_MODEL_SUCCESS'
export const UPDATE_ML_MODEL_FAIL = 'UPDATE_ML_MODEL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
