export const GET_ALL_O365_CUSTOMERS_REQUESTS = 'GET_ALL_O365_CUSTOMERS_REQUESTS'
export const GET_ALL_O365_CUSTOMERS_SUCCESS = 'GET_ALL_O365_CUSTOMERS_SUCCESS'
export const GET_ALL_O365_CUSTOMERS_FAIL = 'GET_ALL_O365_CUSTOMERS_FAIL'

export const O365_CUSTOMER_CREATE_REQUEST = 'O365_CUSTOMER_CREATE_REQUEST'
export const O365_CUSTOMER_CREATE_SUCCESS = 'O365_CUSTOMER_CREATE_SUCCESS'
export const O365_CUSTOMER_CREATE_FAIL = 'O365_CUSTOMER_CREATE_FAIL'

export const GET_O365_CUSTOMER_REQUEST = 'GET_O365_CUSTOMER_REQUEST'
export const GET_O365_CUSTOMER_SUCCESS = 'GET_O365_CUSTOMER_SUCCESS'
export const GET_O365_CUSTOMER_FAIL = 'GET_O365_CUSTOMER_FAIL'

export const UPDATE_O365_CUSTOMER_REQUEST = 'UPDATE_O365_CUSTOMER_REQUEST'
export const UPDATE_O365_CUSTOMER_SUCCESS = 'UPDATE_O365_CUSTOMER_SUCCESS'
export const UPDATE_O365_CUSTOMER_FAIL = 'UPDATE_O365_CUSTOMER_FAIL'

export const FILTER_O365_CUSTOMER_REQUEST = 'FILTER_O365_CUSTOMER_REQUEST'
export const FILTER_O365_CUSTOMER_SUCCESS = 'FILTER_O365_CUSTOMER_SUCCESS'
export const FILTER_O365_CUSTOMER_FAIL = 'FILTER_O365_CUSTOMER_FAIL'

export const SEARCH_O365_CUSTOMER_REQUEST = 'SEARCH_O365_CUSTOMER_REQUEST'
export const SEARCH_O365_CUSTOMER_SUCCESS = 'SEARCH_O365_CUSTOMER_SUCCESS'
export const SEARCH_O365_CUSTOMER_FAIL = 'SEARCH_O365_CUSTOMER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
