export const GET_ALL_RSS_FEEDS_REQUESTS = 'GET_ALL_RSS_FEEDS_REQUESTS'
export const GET_ALL_RSS_FEEDS_SUCCESS = 'GET_ALL_RSS_FEEDS_SUCCESS'
export const GET_ALL_RSS_FEEDS_FAIL = 'GET_ALL_RSS_FEEDS_FAIL'

export const RSS_FEED_CREATE_REQUEST = 'RSS_FEED_CREATE_REQUEST'
export const RSS_FEED_CREATE_SUCCESS = 'RSS_FEED_CREATE_SUCCESS'
export const RSS_FEED_CREATE_FAIL = 'RSS_FEED_CREATE_FAIL'

export const GET_RSS_FEED_REQUEST = 'GET_RSS_FEED_REQUEST'
export const GET_RSS_FEED_SUCCESS = 'GET_RSS_FEED_SUCCESS'
export const GET_RSS_FEED_FAIL = 'GET_RSS_FEED_FAIL'

export const UPDATE_RSS_FEED_REQUEST = 'UPDATE_RSS_FEED_REQUEST'
export const UPDATE_RSS_FEED_SUCCESS = 'UPDATE_RSS_FEED_SUCCESS'
export const UPDATE_RSS_FEED_FAIL = 'UPDATE_RSS_FEED_FAIL'

export const FILTER_RSS_FEED_REQUEST = 'FILTER_RSS_FEED_REQUEST'
export const FILTER_RSS_FEED_SUCCESS = 'FILTER_RSS_FEED_SUCCESS'
export const FILTER_RSS_FEED_FAIL = 'FILTER_RSS_FEED_FAIL'

export const SEARCH_RSS_FEED_REQUEST = 'SEARCH_RSS_FEED_REQUEST'
export const SEARCH_RSS_FEED_SUCCESS = 'SEARCH_RSS_FEED_SUCCESS'
export const SEARCH_RSS_FEED_FAIL = 'SEARCH_RSS_FEED_FAIL'

export const CONFIGURE_RSS_FEED_REQUEST = 'CONFIGURE_RSS_FEED_REQUEST'
export const CONFIGURE_RSS_FEED_SUCCESS = 'CONFIGURE_RSS_FEED_SUCCESS'
export const CONFIGURE_RSS_FEED_FAIL = 'CONFIGURE_RSS_FEED_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
