export const GET_ALL_SOAR_PRODUCTS_REQUESTS = 'GET_ALL_SOAR_PRODUCTS_REQUESTS'
export const GET_ALL_SOAR_PRODUCTS_SUCCESS = 'GET_ALL_SOAR_PRODUCTS_SUCCESS'
export const GET_ALL_SOAR_PRODUCTS_FAIL = 'GET_ALL_SOAR_PRODUCTS_FAIL'

export const SOAR_PRODUCT_CREATE_REQUEST = 'SOAR_PRODUCT_CREATE_REQUEST'
export const SOAR_PRODUCT_CREATE_SUCCESS = 'SOAR_PRODUCT_CREATE_SUCCESS'
export const SOAR_PRODUCT_CREATE_FAIL = 'SOAR_PRODUCT_CREATE_FAIL'

export const GET_SOAR_PRODUCT_REQUEST = 'GET_SOAR_PRODUCT_REQUEST'
export const GET_SOAR_PRODUCT_SUCCESS = 'GET_SOAR_PRODUCT_SUCCESS'
export const GET_SOAR_PRODUCT_FAIL = 'GET_SOAR_PRODUCT_FAIL'

export const UPDATE_SOAR_PRODUCT_REQUEST = 'UPDATE_SOAR_PRODUCT_REQUEST'
export const UPDATE_SOAR_PRODUCT_SUCCESS = 'UPDATE_SOAR_PRODUCT_SUCCESS'
export const UPDATE_SOAR_PRODUCT_FAIL = 'UPDATE_SOAR_PRODUCT_FAIL'

export const FILTER_SOAR_PRODUCT_REQUEST = 'FILTER_SOAR_PRODUCT_REQUEST'
export const FILTER_SOAR_PRODUCT_SUCCESS = 'FILTER_SOAR_PRODUCT_SUCCESS'
export const FILTER_SOAR_PRODUCT_FAIL = 'FILTER_SOAR_PRODUCT_FAIL'

export const SEARCH_SOAR_PRODUCT_REQUEST = 'SEARCH_SOAR_PRODUCT_REQUEST'
export const SEARCH_SOAR_PRODUCT_SUCCESS = 'SEARCH_SOAR_PRODUCT_SUCCESS'
export const SEARCH_SOAR_PRODUCT_FAIL = 'SEARCH_SOAR_PRODUCT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
