export const GET_ALL_SOAR_CUSTOMERS_REQUESTS = 'GET_ALL_SOAR_CUSTOMERS_REQUESTS'
export const GET_ALL_SOAR_CUSTOMERS_SUCCESS = 'GET_ALL_SOAR_CUSTOMERS_SUCCESS'
export const GET_ALL_SOAR_CUSTOMERS_FAIL = 'GET_ALL_SOAR_CUSTOMERS_FAIL'

export const SOAR_CUSTOMER_CREATE_REQUEST = 'SOAR_CUSTOMER_CREATE_REQUEST'
export const SOAR_CUSTOMER_CREATE_SUCCESS = 'SOAR_CUSTOMER_CREATE_SUCCESS'
export const SOAR_CUSTOMER_CREATE_FAIL = 'SOAR_CUSTOMER_CREATE_FAIL'

export const GET_SOAR_CUSTOMER_REQUEST = 'GET_SOAR_CUSTOMER_REQUEST'
export const GET_SOAR_CUSTOMER_SUCCESS = 'GET_SOAR_CUSTOMER_SUCCESS'
export const GET_SOAR_CUSTOMER_FAIL = 'GET_SOAR_CUSTOMER_FAIL'

export const UPDATE_SOAR_CUSTOMER_REQUEST = 'UPDATE_SOAR_CUSTOMER_REQUEST'
export const UPDATE_SOAR_CUSTOMER_SUCCESS = 'UPDATE_SOAR_CUSTOMER_SUCCESS'
export const UPDATE_SOAR_CUSTOMER_FAIL = 'UPDATE_SOAR_CUSTOMER_FAIL'

export const FILTER_SOAR_CUSTOMER_REQUEST = 'FILTER_SOAR_CUSTOMER_REQUEST'
export const FILTER_SOAR_CUSTOMER_SUCCESS = 'FILTER_SOAR_CUSTOMER_SUCCESS'
export const FILTER_SOAR_CUSTOMER_FAIL = 'FILTER_SOAR_CUSTOMER_FAIL'

export const SEARCH_SOAR_CUSTOMER_REQUEST = 'SEARCH_SOAR_CUSTOMER_REQUEST'
export const SEARCH_SOAR_CUSTOMER_SUCCESS = 'SEARCH_SOAR_CUSTOMER_SUCCESS'
export const SEARCH_SOAR_CUSTOMER_FAIL = 'SEARCH_SOAR_CUSTOMER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
