export const GET_ALL_TAGS_REQUESTS = 'GET_ALL_TAGS_REQUESTS'
export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS'
export const GET_ALL_TAGS_FAIL = 'GET_ALL_TAGS_FAIL'

export const UPDATE_TAGS_REQUEST = 'UPDATE_TAGS_REQUEST'
export const UPDATE_TAGS_SUCCESS = 'UPDATE_TAGS_SUCCESS'
export const UPDATE_TAGS_FAIL = 'UPDATE_TAGS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
