export const GET_ALL_USERS_REQUESTS = 'GET_ALL_USERS_REQUESTS'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST'
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS'
export const USER_CREATE_FAIL = 'USER_CREATE_FAIL'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const FILTER_USER_REQUEST = 'FILTER_USER_REQUEST'
export const FILTER_USER_SUCCESS = 'FILTER_USER_SUCCESS'
export const FILTER_USER_FAIL = 'FILTER_USER_FAIL'

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST'
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS'
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL'

export const GET_TENANT_BY_TENANCY_LEVEL_REQUEST = 'GET_TENANT_BY_TENANCY_LEVEL_REQUEST'
export const GET_TENANT_BY_TENANCY_LEVEL_SUCCESS = 'GET_TENANT_BY_TENANCY_LEVEL_SUCCESS'
export const GET_TENANT_BY_TENANCY_LEVEL_FAIL = 'GET_TENANT_BY_TENANCY_LEVEL_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
