export const GET_ALL_V1_CUSTOMERS_REQUESTS = 'GET_ALL_V1_CUSTOMERS_REQUESTS'
export const GET_ALL_V1_CUSTOMERS_SUCCESS = 'GET_ALL_V1_CUSTOMERS_SUCCESS'
export const GET_ALL_V1_CUSTOMERS_FAIL = 'GET_ALL_V1_CUSTOMERS_FAIL'

export const V1_CUSTOMER_CREATE_REQUEST = 'V1_CUSTOMER_CREATE_REQUEST'
export const V1_CUSTOMER_CREATE_SUCCESS = 'V1_CUSTOMER_CREATE_SUCCESS'
export const V1_CUSTOMER_CREATE_FAIL = 'V1_CUSTOMER_CREATE_FAIL'

export const GET_V1_CUSTOMER_REQUEST = 'GET_V1_CUSTOMER_REQUEST'
export const GET_V1_CUSTOMER_SUCCESS = 'GET_V1_CUSTOMER_SUCCESS'
export const GET_V1_CUSTOMER_FAIL = 'GET_V1_CUSTOMER_FAIL'

export const UPDATE_V1_CUSTOMER_REQUEST = 'UPDATE_V1_CUSTOMER_REQUEST'
export const UPDATE_V1_CUSTOMER_SUCCESS = 'UPDATE_V1_CUSTOMER_SUCCESS'
export const UPDATE_V1_CUSTOMER_FAIL = 'UPDATE_V1_CUSTOMER_FAIL'

export const FILTER_V1_CUSTOMER_REQUEST = 'FILTER_V1_CUSTOMER_REQUEST'
export const FILTER_V1_CUSTOMER_SUCCESS = 'FILTER_V1_CUSTOMER_SUCCESS'
export const FILTER_V1_CUSTOMER_FAIL = 'FILTER_V1_CUSTOMER_FAIL'

export const SEARCH_V1_CUSTOMER_REQUEST = 'SEARCH_V1_CUSTOMER_REQUEST'
export const SEARCH_V1_CUSTOMER_SUCCESS = 'SEARCH_V1_CUSTOMER_SUCCESS'
export const SEARCH_V1_CUSTOMER_FAIL = 'SEARCH_V1_CUSTOMER_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
