export const GET_ALL_V1_PRODUCTS_REQUESTS = 'GET_ALL_V1_PRODUCTS_REQUESTS'
export const GET_ALL_V1_PRODUCTS_SUCCESS = 'GET_ALL_V1_PRODUCTS_SUCCESS'
export const GET_ALL_V1_PRODUCTS_FAIL = 'GET_ALL_V1_PRODUCTS_FAIL'

export const V1_PRODUCT_CREATE_REQUEST = 'V1_PRODUCT_CREATE_REQUEST'
export const V1_PRODUCT_CREATE_SUCCESS = 'V1_PRODUCT_CREATE_SUCCESS'
export const V1_PRODUCT_CREATE_FAIL = 'V1_PRODUCT_CREATE_FAIL'

export const GET_V1_PRODUCT_REQUEST = 'GET_V1_PRODUCT_REQUEST'
export const GET_V1_PRODUCT_SUCCESS = 'GET_V1_PRODUCT_SUCCESS'
export const GET_V1_PRODUCT_FAIL = 'GET_V1_PRODUCT_FAIL'

export const UPDATE_V1_PRODUCT_REQUEST = 'UPDATE_V1_PRODUCT_REQUEST'
export const UPDATE_V1_PRODUCT_SUCCESS = 'UPDATE_V1_PRODUCT_SUCCESS'
export const UPDATE_V1_PRODUCT_FAIL = 'UPDATE_V1_PRODUCT_FAIL'

export const FILTER_V1_PRODUCT_REQUEST = 'FILTER_V1_PRODUCT_REQUEST'
export const FILTER_V1_PRODUCT_SUCCESS = 'FILTER_V1_PRODUCT_SUCCESS'
export const FILTER_V1_PRODUCT_FAIL = 'FILTER_V1_PRODUCT_FAIL'

export const SEARCH_V1_PRODUCT_REQUEST = 'SEARCH_V1_PRODUCT_REQUEST'
export const SEARCH_V1_PRODUCT_SUCCESS = 'SEARCH_V1_PRODUCT_SUCCESS'
export const SEARCH_V1_PRODUCT_FAIL = 'SEARCH_V1_PRODUCT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
